const FOOD_DATA = [
  {
    "id": "mixed_fruits",
    "name": "Mixed Fruits",
    "category": "Fruits",
    "rating": "best",
    "quantity": "600–700 g",
    "calories": 300,
    "unit": "serving",
    "protein": 5,
    "notes": "Mix watermelon, muskmelon, apple, banana, mango etc. Calories vary by mix."
  },
  {
    "id": "mixed_salad",
    "name": "Mixed Salad",
    "category": "Salad",
    "rating": "best",
    "quantity": "600–700 g",
    "calories": 180,
    "unit": "serving",
    "protein": 7,
    "notes": "Cucumber, tomato, onion, lettuce/greens, capsicum and green chilli. Avoid creamy dressings."
  },
  {
    "id": "boiled_chana",
    "name": "Boiled Chana",
    "category": "Boiled/Cooked",
    "rating": "best",
    "quantity": "300 g",
    "calories": 492,
    "unit": "serving",
    "protein": 27,
    "notes": "Cooked weight."
  },
  {
    "id": "boiled_chole_matar",
    "name": "Boiled Chole + White Matar Mix",
    "category": "Boiled/Cooked",
    "rating": "best",
    "quantity": "1 bowl (~250 g)",
    "calories": 350,
    "unit": "serving",
    "protein": 19,
    "notes": "Approximate mixed value."
  },
  {
    "id": "dal",
    "name": "Dal",
    "category": "Boiled/Cooked",
    "rating": "best",
    "quantity": "1 bowl",
    "calories": 220,
    "unit": "serving",
    "protein": 12,
    "notes": "Calories depend on tadka/oil."
  },
  {
    "id": "rajma",
    "name": "Rajma",
    "category": "Boiled/Cooked",
    "rating": "best",
    "quantity": "1 bowl",
    "calories": 230,
    "unit": "serving",
    "protein": 15,
    "notes": "Cooked."
  },
  {
    "id": "tofu",
    "name": "Tofu",
    "category": "Protein",
    "rating": "best",
    "quantity": "200 g",
    "calories": 240,
    "unit": "serving",
    "protein": 26,
    "notes": "Brand varies."
  },
  {
    "id": "soy_chunks",
    "name": "Soy Chunks",
    "category": "Protein",
    "rating": "best",
    "quantity": "50 g dry",
    "calories": 170,
    "unit": "serving",
    "protein": 26,
    "notes": "Dry weight."
  },
  {
    "id": "roasted_chana",
    "name": "Roasted Chana",
    "category": "Snack/Protein",
    "rating": "good",
    "quantity": "50 g",
    "calories": 180,
    "unit": "serving",
    "protein": 10,
    "notes": "Keep portion controlled."
  },
  {
    "id": "peanuts",
    "name": "Peanuts",
    "category": "Snack",
    "rating": "good",
    "quantity": "30 g",
    "calories": 171,
    "unit": "serving",
    "protein": 8,
    "notes": "Healthy but calorie dense."
  },
  {
    "id": "atta_roti",
    "name": "Gehu Atta Roti",
    "category": "Grain",
    "rating": "good",
    "quantity": "1 medium",
    "calories": 110,
    "unit": "serving",
    "protein": 3.5,
    "notes": "No ghee/oil added."
  },
  {
    "id": "besan_chilla",
    "name": "Besan Chilla",
    "category": "Breakfast",
    "rating": "good",
    "quantity": "1 medium",
    "calories": 185,
    "unit": "serving",
    "protein": 7.5,
    "notes": "Assumes modest oil."
  },
  {
    "id": "idli",
    "name": "Idli",
    "category": "Breakfast",
    "rating": "good",
    "quantity": "1 medium",
    "calories": 65,
    "unit": "serving",
    "protein": 2,
    "notes": "Sambar can be added separately."
  },
  {
    "id": "poha",
    "name": "Poha",
    "category": "Breakfast",
    "rating": "good",
    "quantity": "1 bowl",
    "calories": 300,
    "unit": "serving",
    "protein": 6,
    "notes": "Oil, peanuts and sev can increase calories."
  },
  {
    "id": "paneer",
    "name": "Paneer",
    "category": "Protein/Dairy",
    "rating": "good",
    "quantity": "150 g",
    "calories": 420,
    "unit": "serving",
    "protein": 27,
    "notes": "Calorie dense; 300 g is roughly 840 kcal."
  },
  {
    "id": "boiled_eggs",
    "name": "Boiled Eggs",
    "category": "Protein",
    "rating": "good",
    "quantity": "2 whole",
    "calories": 150,
    "unit": "serving",
    "protein": 13,
    "notes": "Only if included in your diet."
  },
  {
    "id": "banana",
    "name": "Banana",
    "category": "Fruit",
    "rating": "good",
    "quantity": "1 medium",
    "calories": 105,
    "unit": "serving",
    "protein": 1.3,
    "notes": "Already counted within mixed-fruit option if part of that mix."
  },
  {
    "id": "watermelon",
    "name": "Watermelon",
    "category": "Fruit",
    "rating": "best",
    "quantity": "700 g",
    "calories": 210,
    "unit": "serving",
    "protein": 4.2,
    "notes": "Optional single-fruit alternative."
  },
  {
    "id": "cucumber",
    "name": "Cucumber",
    "category": "Salad",
    "rating": "best",
    "quantity": "200 g",
    "calories": 30,
    "unit": "serving",
    "protein": 1.4,
    "notes": "Optional if building your own salad."
  },
  {
    "id": "tomato",
    "name": "Tomato",
    "category": "Salad",
    "rating": "best",
    "quantity": "150 g",
    "calories": 27,
    "unit": "serving",
    "protein": 1.4,
    "notes": "Optional if building your own salad."
  },
  {
    "id": "green_chilli",
    "name": "Green Chilli",
    "category": "Salad/Spices",
    "rating": "best",
    "quantity": "20 g",
    "calories": 8,
    "unit": "serving",
    "protein": 0.4,
    "notes": "Use to taste if tolerated."
  },
  {
    "id": "mustard_oil",
    "name": "Mustard Oil",
    "category": "Cooking Fat",
    "rating": "worst",
    "quantity": "1 tbsp",
    "calories": 120,
    "unit": "serving",
    "protein": 0,
    "notes": "Measure it. 4 tbsp adds ~480 kcal."
  },
  {
    "id": "ghee",
    "name": "Ghee",
    "category": "Cooking Fat",
    "rating": "worst",
    "quantity": "1 tsp",
    "calories": 45,
    "unit": "serving",
    "protein": 0,
    "notes": "Easy to overlook."
  },
  {
    "id": "aloo_kachori",
    "name": "Aloo Kachori",
    "category": "Fried",
    "rating": "worst",
    "quantity": "1 piece",
    "calories": 250,
    "unit": "serving",
    "protein": 4,
    "notes": "Homemade size/oil can vary significantly."
  },
  {
    "id": "pyaz_kachori",
    "name": "Pyaz Kachori",
    "category": "Fried",
    "rating": "worst",
    "quantity": "1 piece",
    "calories": 300,
    "unit": "serving",
    "protein": 5,
    "notes": "Typical large kachori."
  },
  {
    "id": "samosa",
    "name": "Samosa",
    "category": "Fried",
    "rating": "worst",
    "quantity": "1 piece",
    "calories": 275,
    "unit": "serving",
    "protein": 5,
    "notes": "Size and oil vary."
  },
  {
    "id": "imarti",
    "name": "Imarti",
    "category": "Sweet",
    "rating": "worst",
    "quantity": "1 piece",
    "calories": 200,
    "unit": "serving",
    "protein": 1,
    "notes": "Size varies."
  },
  {
    "id": "bhujiya",
    "name": "Bhujiya",
    "category": "Snack",
    "rating": "worst",
    "quantity": "50 g",
    "calories": 285,
    "unit": "serving",
    "protein": 7.5,
    "notes": "Very calorie dense."
  },
  {
    "id": "parle_g",
    "name": "Parle-G",
    "category": "Biscuit",
    "rating": "worst",
    "quantity": "10 biscuits",
    "calories": 340,
    "unit": "serving",
    "protein": 5,
    "notes": "Approximate; pack size matters."
  },
  {
    "id": "fried_snacks",
    "name": "Mixed Fried Snacks",
    "category": "Fried",
    "rating": "worst",
    "quantity": "100 g",
    "calories": 550,
    "unit": "serving",
    "protein": 7,
    "notes": "Highly variable."
  },
  {
    "id": "kurkure",
    "name": "Kurkure",
    "category": "Snack",
    "rating": "worst",
    "quantity": "1 small packet",
    "calories": 140,
    "unit": "serving",
    "protein": 2,
    "notes": "Approximate."
  },
  {
    "id": "maggie_masala",
    "name": "Maggi Masala-a-Magic",
    "category": "Seasoning",
    "rating": "good",
    "quantity": "1 sachet (6 g)",
    "calories": 13,
    "unit": "serving",
    "protein": 0.3,
    "notes": "Calories are small; sodium is more relevant."
  }
];